sudo: required

language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - extra

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - addon-google_apis-google-28

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-28
    - sys-img-armeabi-v7a-android-26
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

before_install:
- yes | sdkmanager "platforms;android-28"
- chmod +x gradlew
script:
- ./gradlew clean build check