sudo: false
os: linux
language: android
jdk: oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.2
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

before_install:
- yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"
- chmod +x gradlew
script:
- android list target
- ./gradlew clean build check

before_deploy:
  - git config --local user.email "builds@travis-ci.com"
  - git config --local user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://${$GH_TOKEN}github.com/MGabor11/WeatherCheckerApp --tags

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-debug.apk
  skip_cleanup: true
  on:
    all_branches: true
    tags: false


after_deploy:
- rm -rf $TRAVIS_BUILD_DIR/app/build/outputs